# Generated by Django 2.0.2 on 2018-03-01 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('color', models.CharField(blank=True, max_length=128, null=True)),
                ('iframe', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrickLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('col_id', models.IntegerField()),
                ('brick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Brick')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Muro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='muro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Muro'),
        ),
        migrations.AddField(
            model_name='bricklocation',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.Dashboard'),
        ),
    ]
