# Generated by Django 2.0.2 on 2018-03-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muro',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
