# Generated by Django 2.0.2 on 2018-03-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_auto_20180301_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
