# Generated by Django 2.0.2 on 2018-03-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_dashboard_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='muro',
        ),
        migrations.AddField(
            model_name='muro',
            name='dashboards',
            field=models.ManyToManyField(to='dashboards.Dashboard'),
        ),
    ]
