# Generated by Django 2.0.2 on 2018-03-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_auto_20180301_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='fromtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='totime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
