# Generated by Django 2.0.2 on 2018-04-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_auto_20180316_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='brick',
            name='refresh_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
