# Generated by Django 2.0.2 on 2018-04-24 06:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_brick_refresh_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='days_active',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=13, null=True),
        ),
    ]
