# Generated by Django 2.0.2 on 2018-04-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_dashboard_days_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='brick',
            name='image_style',
            field=models.CharField(choices=[('cover', 'Cover'), ('centered', 'Centered')], default='cover', max_length=128),
        ),
    ]
