# Generated by Django 2.0.2 on 2018-04-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_brick_image_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bricklocation',
            options={'ordering': ('row_id', 'col_id')},
        ),
        migrations.AddField(
            model_name='brick',
            name='embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
